export const surpriseMePrompts = [
    'A magical floating island with cascading waterfalls and lush greenery, digital art',
    'An ancient temple hidden deep within a jungle, illuminated by shafts of sunlight',
    'A group of astronauts exploring a mysterious alien landscape, photography',
    'A mystical portal leading to an alternate dimension, surrounded by swirling energy',
    'A fantastical cityscape where skyscrapers are built atop giant mushrooms, digital art',
    'A celestial dragon soaring through the cosmos, leaving trails of stardust in its wake',
    'A whimsical tea party in a enchanted garden, attended by talking animals and fairies, digital art',
    'A magical forest inhabited by friendly woodland creatures and glowing fireflies, digital art',
    'A secret underground laboratory filled with futuristic technology and glowing neon lights',
    'A peaceful village nestled in the rolling hills of the countryside, surrounded by fields of flowers, digital art',
    'A mysterious abandoned castle shrouded in mist, with ivy-covered walls and hidden passages',
    'A surreal dreamscape where reality bends and shifts, digital art',
    'A futuristic cityscape at night, with neon lights reflecting off rain-soaked streets, digital art',
    'A mythical creature emerging from the depths of a dark forest, illuminated by moonlight, digital art',
    'An ancient underwater civilization hidden beneath the waves, with ruins of ornate buildings and statues, digital art',
    'A futuristic space station orbiting a distant planet, with sleek metallic architecture and bustling activity, digital art',
    'A magical library where books come to life and characters step out of the pages, digital art',
    'A majestic phoenix rising from the ashes, surrounded by flames and glowing embers, digital art',
    'An otherworldly landscape of floating islands and crystal-clear waterfalls, digital art',
    'A whimsical fairytale castle perched atop a hill, with turrets and spires reaching towards the sky, digital art',
    'A mystical forest filled with glowing mushrooms and ethereal creatures, digital art',
    'An enchanted garden where flowers bloom in every color of the rainbow, surrounded by sparkling fairy lights, digital art',
    'A futuristic city skyline with flying cars zipping between towering skyscrapers, digital art',
    'A magical potion shop filled with bubbling cauldrons and shelves lined with colorful bottles, digital art',
    'A serene mountain lake reflecting snow-capped peaks and fluffy white clouds, digital art',
    'An alien landscape with strange rock formations and alien plants, bathed in the light of a distant sun, digital art',
    'A mythical creature sanctuary hidden deep within a dense forest, where unicorns and dragons roam free, digital art',
    'An underwater city inhabited by mermaids and sea creatures, with towering coral reefs and bioluminescent jellyfish, digital art',
    'A futuristic cyberpunk cityscape with towering skyscrapers and neon signs, digital art',
    'A magical winter wonderland with snow-covered trees and twinkling fairy lights, digital art',
    'An ancient ruins shrouded in mist, with crumbling columns and hidden treasures, digital art',
    'A whimsical village inhabited by friendly gnomes and elves, with colorful mushroom houses and winding cobblestone streets, digital art',
    'An alien spaceship flying through a colorful nebula, surrounded by swirling clouds of stardust, digital art',
    'A mystical forest glade bathed in the light of a full moon, with fireflies dancing among the trees, digital art',
    'A futuristic city skyline with towering skyscrapers and flying cars zipping through the air, digital art',
    'A magical underwater kingdom ruled by mermaids and sea creatures, with coral palaces and underwater gardens, digital art',
    'An enchanted forest filled with ancient trees and glowing mushrooms, where fairies and spirits dwell, digital art',
    'A whimsical steampunk cityscape with towering clockwork buildings and airships soaring through the sky, digital art',
    'A mystical desert oasis with palm trees and sparkling blue water, surrounded by golden sand dunes, digital art',
    'A futuristic space station orbiting a distant planet, with sleek metallic architecture and bustling activity, digital art',
    'A mythical creature sanctuary hidden deep within a dense forest, where unicorns and dragons roam free, digital art',
    'An underwater city inhabited by mermaids and sea creatures, with towering coral reefs and bioluminescent jellyfish, digital art',
    'A futuristic cyberpunk cityscape with towering skyscrapers and neon signs, digital art',
    'A magical winter wonderland with snow-covered trees and twinkling fairy lights, digital art',
    'An ancient ruins shrouded in mist, with crumbling columns and hidden treasures, digital art',
    'A whimsical village inhabited by friendly gnomes and elves, with colorful mushroom houses and winding cobblestone streets, digital art',
    'An alien spaceship flying through a colorful nebula, surrounded by swirling clouds of stardust, digital art',
    'A mystical forest glade bathed in the light of a full moon, with fireflies dancing among the trees, digital art',
    'A futuristic city skyline with towering skyscrapers and flying cars zipping through the air, digital art',
    'A magical underwater kingdom ruled by mermaids and sea creatures, with coral palaces and underwater gardens, digital art',
    'An enchanted forest filled with ancient trees and glowing mushrooms, where fairies and spirits dwell, digital art',
    'A whimsical steampunk cityscape with towering clockwork buildings and airships soaring through the sky, digital art',
    'A mystical desert oasis with palm trees and sparkling blue water, surrounded by golden sand dunes, digital art',
  ];
  